import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service & Legal Disclaimer",
  description:
    "Terms of service, legal disclaimer, and limitations for idonthaveawill.com. This tool is not legal advice and is not a substitute for an attorney.",
  alternates: {
    canonical: "https://idonthaveawill.com/terms",
  },
  robots: {
    index: false,
    follow: true,
  },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold text-[var(--color-brand)] mb-8">
        Terms of Service & Legal Disclaimer
      </h1>

      <div className="prose prose-gray max-w-none space-y-6">
        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            Not Legal Advice
          </h2>
          <p className="text-gray-600 leading-relaxed">
            idonthaveawill.com provides a self-help tool for creating a simple
            last will and testament. This tool is NOT a law firm, does NOT
            provide legal advice, and is NOT a substitute for the advice of an
            attorney. The information and documents generated by this tool are
            provided for general informational purposes only.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            No Attorney-Client Relationship
          </h2>
          <p className="text-gray-600 leading-relaxed">
            Use of this tool does not create an attorney-client relationship
            between you and idonthaveawill.com or any of its operators. We do
            not review your answers for legal sufficiency, draw legal
            conclusions, provide specific legal advice, or apply the law to your
            individual circumstances.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            Limitations
          </h2>
          <p className="text-gray-600 leading-relaxed">
            This tool generates a SIMPLE will. It is not appropriate for complex
            estate planning situations including but not limited to: estates
            involving business interests, trusts, tax planning strategies,
            blended families with complex custody arrangements, assets in
            multiple countries, or significant charitable giving. For these
            situations, consult an estate planning attorney.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            Your Responsibility
          </h2>
          <p className="text-gray-600 leading-relaxed">
            You are responsible for ensuring the accuracy of all information you
            provide. You are responsible for properly executing your will in
            accordance with your state&apos;s laws (signing, witnessing,
            notarizing as required). You are responsible for determining whether
            a simple will is appropriate for your situation.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            Limitation of Liability
          </h2>
          <p className="text-gray-600 leading-relaxed">
            idonthaveawill.com and its operators shall not be liable for any
            damages arising from the use of this tool, including but not limited
            to direct, indirect, incidental, punitive, and consequential
            damages. Use this tool at your own risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            Data Privacy
          </h2>
          <p className="text-gray-600 leading-relaxed">
            Your will content is generated entirely within your web browser and
            never leaves your device. We collect anonymized, aggregate usage
            statistics (such as state selection and feature usage rates) that
            contain no personally identifiable information. If you opt in to
            email reminders, we store your email address and state only. See
            our Privacy Policy for full details.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-[var(--color-brand)]">
            Affiliate Disclosure
          </h2>
          <p className="text-gray-600 leading-relaxed">
            This site may contain links to third-party attorney referral
            services, state bar associations, and other legal service
            providers. Some of these links may be affiliate links, meaning we
            may receive a referral fee or commission at no additional cost to
            you. This does not influence our recommendations. We only link to
            services we believe are legitimate and helpful. Your will drafting
            tool is and will always remain free to use.
          </p>
        </section>
      </div>
    </div>
  );
}
